### ISSUE TITLE
Current User information should be available via app.

### ISSUE THREAD

**Issue by Earthii** [jusleg/soen341#131]
- [x] Make user info available via app 
**Estimated time:** 2h
**Risk:** HIGH
**Priority:** HIGH
- [x] Add Role
**Estimated time:** 2h
**Risk:** HIGH
**Priority:** HIGH

- [x] Link classMod to Class Model
**Estimated time:** 2h
**Risk:** HIGH
**Priority:** HIGH
<hr>

**Context**

Currently you are able to log in by providing credentials. This will route you to the app but your user information is not in the app at all. 

This means that the app does not have access to current user information such as the current user's classes.

**Comment by miisaka** [comment]
I have added an api route /api/currentUser that will return a JSON object containing all the logged in user's information including the classes.

**Comment by miisaka** [comment]
Tests to be done: @almiche @StevenHaa 
1) The API endpoint /api/currentUser should return 200 OK
2) The Online boolean should be present inside the session object

**Comment by miisaka** [comment]
Are the test cases done for this issue? @almiche @StevenHaa

**Comment by StevenHaa** [comment]
Working on it @miisaka

**Comment by miisaka** [comment]
Unit test: https://github.com/jusleg/soen341/blob/master/Test/test.js#L56
