### ISSUE TITLE
As a teacher, I should be able to create a new class and load a csv file of all my students

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#135]
- [ ] a checkbox should be added to the registration for teachers to sign up
**Estimated hours:** 0.5 hours
**Risk:** LOW
**Priority:** LOW

- [x] a page should be created to add a new class (name of class, hour, location, TAs and students list in csv format) This page should only be visible to teachers
**Estimated hours:** 2 hours
**Risk:** LOW
**Priority:** LOW

- [x] when the csv is loaded, create a new class in the db and add it to every student in the csv
**Estimated hours:** 3 hours
**Risk:** HIGH
**Priority:** HIGH

- [x] send a email to every student in that class indicating that the class has been added to their account
**Estimated hours:** 2 hours
Risk: HIGH
Priority: LOW

### Story points: 13

**Comment by brendanmcgarry** [comment]
All tasks besides teacher checkbox complete.
Teacher checkbox could be moved to next issue due to issues with administrator verification/setting role upon new account creation based on checkbox.

**Comment by StevenHaa** [comment]
![testcase135.png](http://i.imgur.com/QeWgHll.png)

**Comment by brendanmcgarry** [comment]
Note: Certain fields currently require specific formtting:
- Course code: "AAAA###(AAA...)" (four chars, three nums, then optional chars)
- TAs: "email:name,email:name,..."
