### ISSUE TITLE
Setup Backend Environment 

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#16]
- [x] Acquire Digital Ocean server
- [x] Setup backend framework
- [x] Install Node
- [x] Install Apache 2
- [x] Setup MongoDB
- [x] User accounts with limited privileges 
- [x] Firewall

**Comment by Earthii** [comment]
Express is setup with it's core dependencies

**Comment by jusleg** [comment]
Services:
* Node is installed
* Apache 2 was installed
* MongoDB was setup

Administration:
* user accounts with limited privileges were created
* firewall only allow connections to specific port (including mongo and node)

**Comment by Earthii** [comment]
Completed, good job!
