### ISSUE TITLE
Create gravatar link on registration

### ISSUE THREAD

**Issue by Earthii** [jusleg/soen341#163]
- [x] Add new field in user collection: imglink (String to save gravatar image link) 
**Estimated time :** 0.3h
**Risk:** HIGH
**Priority:** HIGH

- [x] Include new field in user.js model
**Estimated time :** 0.2h
**Risk:** LOW
**Priority:** HIGH

- [x] On signup, Insert MD5 hash of email in gravatar link and store the result in imglink
**Estimated time :** 0.5h
**Risk:** LOW
**Priority:** HIGH

**Comment by jusleg** [comment]
We should implement gravatar. It only needs the md5 hash of the user email (which we already have) we set the image src as `https://www.gravatar.com/avatar/HASH` and gravatar will either return the user's picture on social networks or a github generated avatar picture. Using gravatar, we do not need to store any additional field. We could store the hash if we want to improve load speed, but this is just an optimization, not a requirement. More info -> https://en.gravatar.com/site/implement/images/

**Comment by brendanmcgarry** [comment]
To generate the hashed email required for gravatar, we can use the CryptoJS encryption library that our project is already using, like this:
```
let crypto = require('crypto-js');
let email = ... // user email
let hash = crypto.MD5(email.trim().toLowerCase()).toString();
```

**Comment by jusleg** [comment]
wow pretty neat
