### ISSUE TITLE
Clean up code style

### ISSUE THREAD

**Issue by Earthii** [jusleg/soen341#167]
- [x] Using Babel 6, convert the whole code in the project into a uniform coding style

**Estimated time**: 2h

**Comment by miisaka** [comment]
Babel's js coding style has been implemented into what's been done so far. It should be everyone's responsibility to convert their code to Babel's style before committing anything new from this point on. @Earthii  @Ea10 @jusleg @almiche @izconcept @brendanmcgarry @StevenHaa

**Comment by almiche** [comment]
This issue is not done yet

**Comment by miisaka** [comment]
I redid the formatting of the coding style. Now waiting on @Ea10 to finish his part of the formatting to close this issue

**Comment by Ea10** [comment]
It's done @miisaka

**Comment by miisaka** [comment]
Perfect @Ea10 , closing the issue
