### ISSUE TITLE
As a user, I should not be able to login if my account is not validated

### ISSUE THREAD

**Issue by Earthii** [jusleg/soen341#174]
- [x] Add a verification in passport for the validated flag @miisaka 
- [x] flash request with proper message if verification failed @miisaka 
- [x] create connector for get req.flash and show a sweet alert upon redirect @jusleg 
- [x] when the user creates an acc, it shouldnt redirect inside the app

**Estimated time:** 2.5h
**Risk:** HIGH
**Priority:** HIGH
**Validation:** Try to login with a newly created account but not validated. A popup will appear and ask to validate. The user can pick to resend the email.

### Story Points: 3

**Comment by StevenHaa** [comment]
![testcase174](http://i.imgur.com/ms2smDb.png)
