### ISSUE TITLE
Setup front end environment

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#18]
- [x] Download IDE
- [x]  Determine required dependencies
- [x] Get AngularJS and other dependencies
- [x] Get SCSS and make required change to allow SCSS -> CSS convertion (Sass CLI)

**Comment by Earthii** [comment]
Install Grunt/ Gulp

**Comment by izconcept** [comment]
Installed WebStorm

**Comment by StevenHaa** [comment]
installed Webstorm

**Comment by Earthii** [comment]
@almiche Don't close issues that are not related to you. This has not been completed.
