### ISSUE TITLE
As a user, I should be notified if my password combination was wrong

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#187]
**Estimated time:** 0.5h
**Risk:** LOW
**Priority:** HIGH

### Story Points: 1

**Comment by jusleg** [comment]
@StevenHaa or @Ea10 can you make a test case

**Comment by almiche** [comment]
![testcase187](https://cloud.githubusercontent.com/assets/14715156/24943117/ef848d38-1f22-11e7-9969-781d0c1e3a33.PNG)
