### ISSUE TITLE
Determine Database schema

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#19]
- [x] Create schema
- [x]  Put the schema in wiki

**Comment by almiche** [comment]
- We need to determine what type of database is being used either mongoDB or a SQL variant

- Create a basic database schema to house the chats

**Comment by Earthii** [comment]
I Believe we're leaning towards SQL because it provides a relational database.

**Comment by almiche** [comment]
Closed story by accident. SQL sounds good @Earthii !

**Comment by almiche** [comment]
After discussing it with Brendan we decided to go with a MongoDB database

**Comment by brendanmcgarry** [comment]
Determined database schema for first sprint:
![soen-341-database-schema-sprint1](https://cloud.githubusercontent.com/assets/6577214/22521444/0078f90e-e886-11e6-89e7-8dd1a41d561e.png)

**Comment by jusleg** [comment]
https://github.com/jusleg/soen341/wiki/Database-Schema
