### ISSUE TITLE
As a user, I should be able to verify my account

### ISSUE THREAD

**Issue by Earthii** [jusleg/soen341#195]
- [x] Provide a way for the user to get a new verification email if the first one is lost

**Risk:** HIGH
**Priority:** HIGH
**Estimated time:** 2h

### Story Points: 3

**Comment by jusleg** [comment]
I think this is not important. We have some critical things that we need to do. This is not a concern at this moment

**Comment by jusleg** [comment]
@Ea10 or @StevenHaa we'll need test for that

**Comment by jusleg** [comment]
@almiche can you add you reverification fix

**Comment by almiche** [comment]
![195](https://cloud.githubusercontent.com/assets/14715156/24942017/4b434a26-1f1c-11e7-973c-cb86f416d70a.PNG)

**Comment by almiche** [comment]
Unit test being used [https://github.com/jusleg/soen341/blob/master/Test/test.js#L75](https://github.com/jusleg/soen341/blob/master/Test/test.js#L75)
