### ISSUE TITLE
REGEX for class code not accurate 

### ISSUE THREAD

**Issue by Earthii** [jusleg/soen341#196]
<img width="697" alt="screen shot 2017-03-31 at 9 08 54 am" src="https://cloud.githubusercontent.com/assets/16367621/24551777/c145cad4-15f1-11e7-9ec4-7567a21a9e03.png">

**Comment by jusleg** [comment]
@Earthii Please give me examples of valid and invalid class names and I will fix the regex

**Comment by Earthii** [comment]
As our Slack convo says : 
"Currently it's "AAAA###" (4 chars, 3 nums) with optional alphanums/spaces/hyphens at the end (eg AAAA###JJ-3)"

**Comment by jusleg** [comment]
^([A-Za-z]{4})[ ]?([0-9]{3,4})([ -]?([a-zA-Z]{1,2}([-][a-zA-Z])?))?$

![img](http://i.imgur.com/sePoDEm.png)

Full match: department+number+section

if you only want a specific part use the following catch groups
group 1 : department
group 2: course number
group 4: section

**Comment by Earthii** [comment]
#214
