### ISSUE TITLE
Basic hello world page to test front end + back end

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#20]
The ideal case would be to have node backend generate 0 display and have only angular app communicate with node server.

- Eric

**Comment by almiche** [comment]
When the server is running mongo is running on port 27017 and we can view a hello world page at 138.197.138.222:27017

**Comment by Earthii** [comment]
It's not complete, node and angular are still not connected

**Comment by Earthii** [comment]
PR has been made to be merged onto master
