### ISSUE TITLE
Side bar should be able to distringuish classUser and classMod

### ISSUE THREAD

**Issue by Earthii** [jusleg/soen341#203]
Currently, there is no difference between a class that one is attending and a class that one is teaching / tutoring. A interface change should be implemented for that purpose

**Estimated time:** 3h

**Comment by izconcept** [comment]
<img width="937" alt="screen shot 2017-04-12 at 9 35 35 am" src="https://cloud.githubusercontent.com/assets/16395051/24960314/69c47e88-1f63-11e7-9205-0caed21264cc.png">

**Comment by izconcept** [comment]
Tests passed.
Issue Closed!
