### ISSUE TITLE
As a user (student or teacher), I should be able to sign in the application using my email and my password

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#25]
- [x] Create universal login UI (teacher and student will log in using the same page)
- [x] implement passport js for the authentification
- [x] Connect passport js with the mongo database
- [x] Make responsive login page

Validation: A dummy user is present in the database, The application should log into the dummy user.

**Story point:** 3

**Comment by izconcept** [comment]
Integrate Facebook OAuth
Integrate G+ OAuth

**Comment by izconcept** [comment]
Improved login UI #72

**Comment by Ea10** [comment]
![#25](http://i.imgur.com/lJ0wQla.png)
