### ISSUE TITLE
Create a login system

### ISSUE THREAD

**Issue by miisaka** [jusleg/soen341#28]
Create username+password login system

- [x] Front-end : Simple Form to be made that will
- [x] Back-end : Login System
- [x] Temporary database of credentials
- [x] Confiugre front end files to run with angular app

**Comment by Earthii** [comment]
Front-end :
Simple Form to be made that will 
Back-end :

**Comment by miisaka** [comment]
For Sprint #1, I will make a simple login system that will allow users to register and login with a basic authentication and the credentials will be saved in a temporary database file as a .json file. The login system will be improved upon in Sprint #2

**Comment by Ea10** [comment]
Front end for the login has been made.

**Comment by Earthii** [comment]
Front end files are there but not configured to run with the Angular app. Check routing.

**Comment by miisaka** [comment]
Backend login system has been completed

**Comment by miisaka** [comment]
Unit test: https://github.com/jusleg/soen341/blob/master/Test/test.js#L121
