### ISSUE TITLE
Create DB with new schema

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#49]
- [x]  Create the database in the server
- [x] Create user collection (name, email, hashed password, list of classes, list of classes moderating, additional data)
- [x] Create class collection (name, professor, classroom, time, chat object)
- [x]  Add documentation about new schema on the [wiki](https://github.com/jusleg/soen341/wiki)

**Comment by jusleg** [comment]
Database has been created and is now live on the server

**Comment by izconcept** [comment]
Added improved documentation https://github.com/jusleg/soen341/wiki/Database-Documentation
