### ISSUE TITLE
As a teacher, I should be able to sign up using my name, concordia email and a valid password

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#51]
- [x] Create UI for teacher sign up
- [x] Verify the password (minimum length 8, uppercase and lowercase, number and special characters)
- [x] Verify the email using a regex
- [x] Add teacher account to database, implement using PassportJs

Validation:
  * use a test string to verify that the password regex work
  * use a test string to verify that the email regex work
  * verify that a user can be created by creating a dummy user then deleting it

**Story point:** 3
**Time estimation:** 8hr

**Comment by miisaka** [comment]
All the subtasks has been completed, awaiting review on Pull request to close this issue.

**Comment by almiche** [comment]
Unit test used [https://github.com/jusleg/soen341/blob/master/Test/test.js#L131](url)
