### ISSUE TITLE
AES-256 token generation

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#67]
- [x]  install node plugin to support aes-256
**Estimated hours:** 1 hours 
**Risk:** LOW
**Priority:** HIGH
- [x] pick a master decrypt password
**Estimated hours:** 0.1 hours 
**Risk:** LOW
**Priority:** LOW
- [x] test encrypt / decrypt
**Estimated hours:** 7 hours 
**Risk:** HIGH
**Priority:** HIGH

### **Story Points:** 3

Validation: Encrypt a message, decrypt it and verify if the resulting string matches the initial string

**Comment by jusleg** [comment]
password is: ch3vald3gu3rr3ftwgr8b8m8

**Comment by jusleg** [comment]
I found a tutorial on how to use a library to do the encryption and decryption
http://stackoverflow.com/questions/18279141/javascript-string-encryption-and-decryption
Two function will have to be built: encrypt(message) and decrypt(message). The passphrase would always be the same; therefore we do not need it in the method signature. 

Here is an example using cryptojs. The methods would just call cryptojs. The script at this url: [https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js](https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/rollups/aes.js) should also be imported into our project so that we can use cryptojs

`var encrypted = CryptoJS.AES.encrypt("Message", "Secret Passphrase");
//U2FsdGVkX18ZUVvShFSES21qHsQEqZXMxQ9zgHy+bu0=

var decrypted = CryptoJS.AES.decrypt(encrypted, "Secret Passphrase");
//4d657373616765
`

**Comment by brendanmcgarry** [comment]
Installed the aes-256 package on the server via
```
sudo npm install crypto-js
```

**Comment by brendanmcgarry** [comment]
AES module usage:
```
const aes = require('./app/aes.js');

aes.encrypt(aes.encrypt("msgToEncrypt"));
// ex return value: U2FsdGVkX18ZUVvShFSES21qHsQEqZXMxQ9zgHy+bu0=

aes.encrypt(aes.decrypt("encryptedMsg"));
// returns original message
```

**Comment by jusleg** [comment]
You could put it in the documentation

**Comment by miisaka** [comment]
Unit test: https://github.com/jusleg/soen341/blob/master/Test/test.js#L97
https://github.com/jusleg/soen341/blob/master/Test/test.js#L108
