### ISSUE TITLE
As a user who is signed in, I should be able to sign out using the sign out option in the dropdown of the chat

### ISSUE THREAD

**Issue by jusleg** [jusleg/soen341#69]
- [x] Add sign out button in the chat UI
- [x] de-authenticate the user once the button is clicked
- [x] redirect back to the home page

Validation: A user should be logged in and then logged out. The chat url should be queried. The application should redirect back to the landing page.

The logout feature can only be implemented once the session has been fixed (bug issue #90 )

**Story point:** 1
**Time estimation:** 2hr

**Comment by miisaka** [comment]
This will be done in sprint 3 due to lack of time.

**Comment by miisaka** [comment]
The logout feature can only be implemented once the session has been fixed (bug issue #90 )

**Comment by StevenHaa** [comment]
![testcase69](http://i.imgur.com/ysxAR4U.png)
