### ISSUE TITLE
As a user, I should see who is online in the class.

### ISSUE THREAD

**Issue by Earthii** [jusleg/soen341#92]
Check
https://www.npmjs.com/package/socket.io.users

- [x] Create Api call to get the number of users online
**Estimated time :** 5h

- [x] Add new section in chat window and display the amount of online users with angular
**Estimated time :** 3h

- [x] refactor current content window to contain both chat section and new section
**Estimated time :** 3h

**Risk:** HIGH
**Priority:** HIGH
**Validation:** Log in the app. check the counter. While still being logged in, log in using another device and another account. The number will increase by 1. Upon disconnection , the number will decrease by 1.

### **Story Point :** 8

**Comment by jusleg** [comment]
Moved to the next sprint.

**Comment by miisaka** [comment]
API call has been made to get the number of users online. Just needs to be linked to frontend through Angular @StevenHaa @Earthii

**Comment by StevenHaa** [comment]
@miisaka just did it, should i create an issue for it?

**Comment by StevenHaa** [comment]
![img](http://imgur.com/2t6YF3b)

**Comment by miisaka** [comment]
Unit test: https://github.com/jusleg/soen341/blob/master/Test/test.js#L131
